-- ADR 0010 Phase B (continuation-token variant): let an anonymous applicant complete
-- their own decision/offer/accept flow without a login, while the officer-OR-owner gate
-- keeps serial-id IDOR closed.
--
-- POST /applications issues an unguessable per-application continuation token and returns
-- it to the applicant. The application-scoped routes (decision, accept, offer, detail,
-- offer read) authorize on officer OR owner OR a valid continuation token for THAT
-- application id -- so the token is a capability scoped to one application, not a session.
--
-- Nullable: officer-created and pre-migration/legacy rows have no token and remain
-- officer-OR-owner only (no anonymous token path), which is the safe default. A fresh
-- db/init volume and the seed have no legacy rows (seed applications carry an applicant_id
-- and are officer/owner-managed), so this applies cleanly here.
--
-- Compatibility of a NON-fresh volume with in-flight ANONYMOUS applications: before this
-- feature the application-scoped routes were unauthenticated, so an anonymous applicant
-- completed decision/offer/accept with no credential. After this deploy a token is
-- required, and a pre-migration anonymous row has none -- so its logged-out applicant
-- cannot self-serve. This migration deliberately does NOT backfill tokens: a generated
-- token that is never delivered to the applicant (there is no verified email/SMS channel
-- in this platform) does not restore access, so backfill would be false safety.
--
-- Recovery plan for such rows is OFFICER-MEDIATED: officers act on ANY application (the
-- authz officer short-circuit), and the officer underwriting UI now exposes the full
-- flow -- re-run identity check, run decision, make offer, accept -- so an officer can
-- complete or advance a stranded pre-migration application on the applicant's behalf.
-- This mirrors migration 0007's manual-operator recovery rung. A self-serve verified-
-- channel resume flow is out of scope (needs a delivery channel + product sign-off);
-- see adr/0010-application-ownership-authorization.md.
ALTER TABLE applications ADD COLUMN IF NOT EXISTS continuation_token TEXT;
